# Generated by Django 3.0.7 on 2020-07-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
